name: Run unit tests and code coverage
on: ["push", "pull_request"]

jobs:
  test:
    name: Runs unit tests and computes code coverage
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: 3.7
            env:
              - TOXENV: py37
          - os: ubuntu-latest
            python-version: 3.8
            env:
              - TOXENV: py38
          - os: ubuntu-latest
            python-version: 3.8
            env:
              - TOXENV: lint
          - os: ubuntu-latest
            python-version: 3.8
            env:
              - TOXENV: black
          - os: macos-latest
            python-version: 3.7
            env:
              - TOXENV: py37
          - os: macos-latest
            python-version: 3.8
            env:
              - TOXENV: py38
          - os: windows-latest
            python-version: 3.7
            env:
              - TOXENV: py37
          - os: windows-latest
            python-version: 3.8
            env:
              - TOXENV: py38
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install testing tools
      run: pip install -U setuptools tox coveralls

    - name: Run tox with environment :${{ matrix.env.TOXENV }}
      env: ${{ matrix.env }}
      run: tox

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel: true

  finish:
      needs: test
      runs-on: ubuntu-latest
      steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
